apiVersion: v1
kind: Namespace
metadata:
  name: eshop
  labels:
    app.kubernetes.io/name: eshop
    app.kubernetes.io/instance: eshop
---
apiVersion: v1
kind: Secret
metadata:
  namespace: eshop
  name: eshop-secrets
type: Opaque
data:
  MANAGER_EMAIL: {MANAGER_EMAIL}
  MANAGER_PASSWORD: {MANAGER_PASSWORD}
  MANAGER_FULL_NAME: {MANAGER_FULL_NAME}
  MANAGER_COUNTRY: {MANAGER_COUNTRY}
  MANAGER_POSTCODE: {MANAGER_POSTCODE}
  MANAGER_CITY: {MANAGER_CITY}
  MANAGER_ADDRESS: {MANAGER_ADDRESS}
  file_upload_endpoint: {file_upload_endpoint}
  file_upload_accessKey: {file_upload_accessKey}
  WEB_ROOT: {WEB_ROOT}
  WEB_HOST: {WEB_HOST}

