apiVersion: v1
kind: Service
metadata:
  namespace: eshop
  name: eshop-web
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: eshop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eshop
  name: eshop-deployment
  labels:
    app: eshop
spec:
  selector:
    matchLabels:
      app: eshop
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: eshop
    spec:
      containers:
        - name: eshop
          image: maxmorev/eshop-web-v2:latest
          ports:
            - containerPort: 8080
              name: springboot
          resources:
            requests:
              memory: "200Mi"
              cpu: "250m" # 1/4 core
            limits:
              memory: "380Mi"
              cpu: "500m" # 1/2 core
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            timeoutSeconds: 5
            periodSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 100
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 1
          env:
            - name: MANAGER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: MANAGER_EMAIL
            - name: MANAGER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: MANAGER_PASSWORD
            - name: MANAGER_FULL_NAME
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: MANAGER_FULL_NAME
            - name: MANAGER_COUNTRY
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: MANAGER_COUNTRY
            - name: MANAGER_POSTCODE
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: MANAGER_POSTCODE
            - name: MANAGER_CITY
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: MANAGER_CITY
            - name: MANAGER_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: MANAGER_ADDRESS
            - name: file_upload_endpoint
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: file_upload_endpoint
            - name: file_upload_accessKey
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: file_upload_accessKey